"""add_csat

Revision ID: 79bb4de0b4e7
Revises: 7cb906625af1
Create Date: 2026-06-21 00:05:32.942301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bb4de0b4e7'
down_revision: Union[str, None] = '7cb906625af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('csat_rating', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('csat_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'csat_feedback')
    op.drop_column('tickets', 'csat_rating')
    # ### end Alembic commands ###
